name: Build container

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build the binary for x86_64
        run: cross build --release --target x86_64-unknown-linux-musl
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-x86_64
          path: target/x86_64-unknown-linux-musl/release/linux-release-fetcher

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build the binary for arm64
        run: cross build --release --target aarch64-unknown-linux-musl
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-aarch64
          path: target/aarch64-unknown-linux-musl/release/linux-release-fetcher

  build-armv7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build the binary for armv7
        run: cross build --release --target armv7-unknown-linux-musl
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-armv7
          path: target/armv7-unknown-linux-musl/release/linux-release-fetcher

  build-image:
    runs-on: ubuntu-latest
    needs: [build-x86_64, build-arm64, build-armv7]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4